### ISSUE TITLE
Performance: Reduce joins to one node to improve performance

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#197]
Create a rule to transform the LogicalPlan, getting joins between git tables and transforming them to only one node. Doing this we only need to iterate once per repository per join, instead of doing a join between all the repositories (like we are doing on engine project).

As in engine, we should only support Projects, Filter and Table nodes below Joins. If another node type is there, the Join node cannot be optimized.

**Comment by erizocosmico** [comment]
## Proposal (WIP)

The `SquashedTable` (name TBD) would be like a regular gitquery table, only its internal iterator is composed of several potentially chained primitive iterators.

Filters would need to be translated into something that can use the raw go-git objects and executed directly inside the primitive iterators.

### Primitive iterators

We could have a primitive iterator for each kind of object (and table) we need. That way we would end up with:

- `RepositoryIter`
- `RemotesIter(RepositoryIter)`
- `RefsIter(RepositoryIter)`
- `CommitsIter(RefsIter)`
- `TreeEntriesIter(CommitsIter)`
- `BlobsIter(TreeEntriesIter)`

Those primitive iterators return the `go-git` object instead of a `sql.Row`.

### Filters for Raw objects

- `commit_has_blob` would be translated to `give me all blobs from this commit`.
- `commit_has_tree` would be translated to `give me all trees from this commit`.
- `tree_entries.entry_hash = blobs.hash` would be translated to `give me blobs for these tree entries`.
- `repositories.id = refs.repository_id` would be translated to `give me this repo from the pool, then all its references`.
- `repositories.id = remotes.repository_id` would be translated to `give me this repo from the pool, then all its remotes`.
- `refs.hash = commits.hash` will be translated to `give me the commit with this reference hash`.
- `history_idx(refs.hash, commits.hash) $OP $N` would be translated to `given the previous reference,
the idx in the history of this commit if it satisfies $IDX $OP $N` where `$OP` needs to be an integer comparison operator, `$N` needs to be an integer and `$IDX` is the index in the history.
- `repositories.id = $LITERAL` instead of using all repositories, we'll get the one with the `$LITERAL` id from the pool and pass it along.
- `{refs.hash,refs.name} = $LITERAL` instead of using all references, we'll go looking for the one with the hash/name equal to `$LITERAL` and pass it along.
- `commit.hash = $LITERAL` instead of using all commits we'll go looking for the one with the hash equal to `$LITERAL` and pass it along. If it's chained with references it will be checked that it's in the history of the reference.
- `tree_entries.tree_hash = $LITERAL` instead of using all tree entries, we'll go looking for one with the given tree hash and pass it along. If it's chained with commits, it will be checked that such tree is in the commit.
- `blobs.hash = $LITERAL` instead of using all blobs, we'll go looking for one with the given blob hash and pass it along. If it's chained with tree entries we'll check before that tree entry hash matches the blob.
- `commit.tree_hash = tree_entries.tree_hash` will be translated to `give me the tree entries for this commit tree`.

All other filters would just be translated to our own filters that will be evaluated against raw objects. That could lead to a lot of repeated logic if we want to implement all expressions that can potentially appear there. Another option is to just wait until the final row is ready, fix the indexes (if there is a need to do it) and just filter against the final row.

**What if a join does not have any of the previous conditions as a join condition?**

Then we should not squash it. You can do `history_idx(refs.hash, blobs.hash)`, but that does not make sense and will yield 0 rows. We could optimize things like that and automatically return an `EOFIter`.

### Iterator composition

Imagine we want the following queries:

```sql
SELECT * 
FROM refs 
INNER JOIN commits 
  ON history_idx(refs.hash, commits.hash) >= 0
```
```sql
SELECT blobs.* 
FROM refs 
INNER JOIN commits 
  ON history_idx(refs.hash, commits.hash) >= 0
INNER JOIN blobs
  ON commit_has_blob(commit.hash, blob.hash)
```

The two joins in the first query would be squashed into something like:

```
CommitsIter(RefsIter(AllReposIter))
```

The three joins in the first query would be squashed into something like:

```
BlobsIter(TreeEntriesIter(CommitsIter(RefsIter(AllReposIter))))
```

Note that we did not select tree entries, but it's needed to perform the join, since the blob is on the tree entry.

That way, all the missing steps are filled depending on what's missing and what we have using the following graph:

```
REPOS --> REFS --> COMMITS --> TREE ENTRIES --> BLOBS
           \--> REMOTES
```

Note that only missing iterators between the joined tables are added. If the join is between Commits and Blobs, TreeEntries will be added, but Repos and Refs will not, it will just iterate over all commit objects.

### Row composition

**Comment by smola** [comment]
`SquashedTable` might be, indeed, be a good name. I've tried looking for a name used in other databases for this kind of join optimization. The most similar is _merge join_, but it is different enough to prefer a name that does not match this or any other common join optimization.

**Comment by kuba--** [comment]
...just my 2 cents - maybe `ZipTable`?
zip operation is very popular in FP., e.g.:
```
zipWith (+) [1, 2, 3] [4, 5, 6]

[(1, 4), (2, 5), (3, 6)]
```
So maybe it makes sense here - WDYT?
