### ISSUE TITLE
Check how git bitmaps can improve udf speeds

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#199]
Before starting with bitmap implementation on go-git, check in which cases we can improve performance doing this. After enumerate that cases, evaluate if bitmaps are worth it to gitbase.

**Comment by erizocosmico** [comment]
### What data is contained in the bitmap?

Bitmap format is composed by the following things:

- Header
- 4 bitmaps with size M, being M the total number of objects in the repository. There is one per each type of object, in the following order: commits, trees, blobs, tags. If nth bit is 1, means nth object is of that type.
- N entries (one per each commit, N is stored in the header).

The entry looks like this:
- Position in index file
- XOR offset used to compress the bitmap
- some flags
- compressed ewah bitmap

Every entry has a bitmap of size N. By combining all the entries bitmaps we could get a reachability matrix from commit i to commit j if M[i, j] is 1.

### How can we use this for `history_idx`?

`history_idx` would not benefit much from this. While returning a -1 (meaning it's not in history) would be instant because of it, computing the idx would still require traversing the history even if commits are ordered. 

That does not mean we cannot find a solution, though. I can think of two, right now:
- If and only if commits are sorted in history in the bitmap (which I don't think they are but should be worth checking) we could use this if we return idx as if it was a git log, not taking into account that some commits with multiple parents may have different commits with the same index. If that's something we care about, this option can be discarded.
- Implement a `in_history` function. That would be instantaneous with bitmap indexes. Then, if user still wants to know the index, there's no escape from history traversal.

### How can we use this for `commit_has_blob` and `commit_has_tree`?

Easy, we can't. There is no reachability bitmap computed between commits and trees and between commits and blobs.

We could precompute our own reachability matrixes, just like this does, though.

N entries of bitmaps of length M where N is the number of commits and M is the number of trees or blobs (depending on the function we're talking about).

### Problems I see with this format

There is no association between commit hash and index (maybe there is in the index file, but certainly I haven't seen it on the bitmap format spec).

I think for our use case we would need a bit more custom format in order to achieve our goals in terms of performance.

**history_idx**

Again, for no traversal we would need a `in_history` function.

- Total number of commits
- N hash entries, to get the index of the hashes we're looking for. Sorted so we can binary search for it (we can seek for them because we know the total number)
- N entries containing the following:
  - pos of the commit object in the index
  - XOR offset to compress the bitmap
  - compressed bitmap of length N with reachability between commits

If we want to make `history_idx` a think we could also have an index for that adding the following:

- A matrix of NxN where it's contained the index of j in the history of i or -1 if it's not present.

**commit_has_blob**

- Total number of commits
- Total number of blobs
- N commit hash entries, to get the index of the hashes we're looking for. Sorted so we can binary search for it (we can seek for them because we know the total number)
- M blob hash entries, to get the index of the hashes we're looking for. Sorted so we can binary search for it (we can seek for them because we know the total number)
- N entries containing the following:
  - pos of the commit object in the index
  - XOR offset to compress the bitmap
  - compressed bitmap of length M with reachability between commits and blobs

**commit_has_tree**

- Total number of commits
- Total number of trees
- N commit hash entries, to get the index of the hashes we're looking for. Sorted so we can binary search for it (we can seek for them because we know the total number)
- M trees hash entries, to get the index of the hashes we're looking for. Sorted so we can binary search for it (we can seek for them because we know the total number)
- N entries containing the following:
  - pos of the commit object in the index
  - XOR offset to compress the bitmap
  - compressed bitmap of length M with reachability between commits and trees

That would give us blazing fast searches for these cases at the expense of needing three separate indexes, one for each thing.

**Comment by jfontan** [comment]
### Idea for `history_idx` index

If we have to generate the bitmap indexes we can also generate a list of hashes with its distance from the root, for example:

```go
// {hash, distance to root}
{00112233, 0}, // root
{11223344, 1}, // both parents from a merge
{22334455, 1}, 
{33445566, 2},
{44556677, 3},
{55667788, 4},
```

This list can be saved in hash order to be able to do a binary search. In `history_idx` first we check if both hashes are connected with the bitmap index. If this is true then we search both hashes and calculate the distance:

```
history_idx(00112233, 55667788) = abs(0 - 4) = 4
history_idx(11223344, 44556677) = abs(1 - 3) = 2
```

**Comment by erizocosmico** [comment]
What do we consider root? Because a commit can appear in several references

**Comment by jfontan** [comment]
root = The initial commit. I believe it's what we use for rooted repos.

**Comment by jfontan** [comment]
A better explanation of the index:

https://gist.github.com/jfontan/3f21d87d75438c36e9c4fdee29ba0feb#file-history-md

**Comment by erizocosmico** [comment]
Re-read the spec again and turns out I misunderstood something, so edited the proposal above.

**Comment by smola** [comment]
> How can we use this for commit_has_blob and commit_has_tree?
> It's a very simple access and it would improve much the speed of this.

Careful. I would expect `commit_has_blob` and `commit_has_tree` to check blobs and trees in this commit, but not this commit's parents. I think what you would get, at least with a single lookup, is if the blob or trees are reachable from the commit *or any of its acenstors*.

**Comment by erizocosmico** [comment]
We would need to check that. If it's "all reachable from this commit" then we definitely can't use the bitmap index for these two functions.

**Comment by erizocosmico** [comment]
Shall we mark this as blocked, as it needs to be discussed and so on?

**Comment by erizocosmico** [comment]
Yep, we can probably close it

**Comment by erizocosmico** [comment]
@ajnavarro shall we close this?
