### ISSUE TITLE
Implement Table Indexable interface

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#253]
Depends on: https://github.com/src-d/go-mysql-server/issues/169

**Comment by mcarmonaa** [comment]
# Proposal

To implement Indexable interface for those indexable tables we can just have:
```
type indexableTable struct {
	Table
	iter RowRepoIter
        buildIter IterWithSelectorsFunc
	...
}

func (i *indexableTable) IndexKeyValueIter(colNames []string) (sql.IndexKeyValueIter, error) { ... }
func (i *indexableTable) WithProjectFiltersAndIndex(columns, filters []sql.Expression, index sql.IndexValueIter) (sql.RowIter, error) { ... }
```

Then, to make a table indexable is only necessary return in its own constructor as an instance of this struct, e.g:
```
func newBlobsTable() sql.Table {
	return &indexableTable{
		Table: new(blobsTable),
		iter:  &blobIter{readContent: true},
                ...
	}
}
```

To address this solution we must change a couple of interfaces and refactor some code:
- RowRepoIter interface need get two more methods:
```
type RowRepoIter interface {
	NewIterator(*Repository) (RowRepoIter, error)
	new -> CurrentRepository() (repoID, error)
	new ->LastHash() (string, error)
	Next() (sql.Row, error)
	Close() error
}
```

So we can get the repository it's being iterated and the hash of the last object this iterator returned. These values are necessary to build the `sql.IndexKeyValueIter` slices that its method `Next()` returns. This slices will be `[valCol1, valCol2, ..., indexValue]`, where indexValue will be a struct containing the `repoID` and `hash`.
```
type indexValue struct {
	ID   string
	Hash string
}
```

In this way, the only changes in the current tables should be add this two new methods to the specific implementation of each table iterator.

-  Add a method `GetByID(id string) *Repository` to the RepositoryPool, so we can get any repo from the pool. To do this, we can refactor some code from the `GetPos` method.

- Create a type `IterWithSelectorsFunc`, which basically will be the anonymous functions that right now are being given to the `rowIterWithSelectors` functions in the `WithProjectAndFilters` [method](https://github.com/src-d/gitbase/blob/master/blobs.go#L98) in each table implementation.

We have to refactor `rowIterWithSelectors` too, taking the first part of this [function](https://github.com/src-d/gitbase/blob/master/filters.go#L336) which will return the specific iterator implementation from the table as `RowRepoIter`. 
```
iterWithSelectors(...) (RepoRowIter, error) { ... }

rowIterWithSelectors(...) sql.RowIter {
rowRepoIter, err := iterWithSelectors(...)
...
}
```

We are interested in this iterator because we can use it to iter on specific repos calling `rowrepoIter.NewIterator(repo)`, something necessary to implement the `WithProjectFiltersAndIndex` method.

- Make `WithProjectFiltersAndIndex(columns, filters []sql.Expression, index sql.IndexValueIter) (sql.RowIter, error)` accept other parameter `ctx sql.Context` to be able to  retrieve the pool repository.

With this changes, we can implement the two `Indexable` interface methods as a general case for any table.

For the `IndexKeyValueIter(colNames []string) (sql.IndexKeyValueIter, error)` method, we would have a specific implementation of the `sql.IndexKeyValueIter`:
```
type indexKVIter struct {
	RowRepoIter
	colIndexes []int
}

...
func (i *indexKVIter) Next() ([]interface{}, error) {
...
	repo, err := i.RowRepoIter.CurrentRepository()
	if err != nil {
		return nil, err
	}

	hash, err := i.RowRepoIter.LastHash()
	if err != nil {
		return nil, err
	}

	idxValue := &indexValue{repo.ID, hash}
...
}
...
```

For the `WithProjectFiltersAndIndex()` method, we can rely on the specific iterators implementations as `WithProjectAndFilters` does in a more general way through the commented changes.
```
func (i *indexableTable) WithProjectFiltersAndIndex(ctx sql.Context, columns, filters []sql.Expression, index sql.IndexValueIter) (sql.RowIter, error) {
	s, ok := ctx.Session.(*Session)
	if !ok || s == nil {
		return nil, ErrInvalidGitbaseSession.New(ctx.Session)
	}

...
	iter := &indexIter{
		idxValueIter: index,
		pool:         s.Pool,
		columns: columns,
		filters: filters,
		schema: i.Table.Schema(),
	}
...
	if len(filters) == 0 {
		return iter, nil
	}

	return plan.NewFilterIter(ctx, expression.JoinAnd(filters...), iter), nil
}

type indexIter struct {
	repoID string
	iter RowRepoIter
	currIter RowRepoIter

	pool         *RepositoryPool
	idxValueIter sql.IndexValueIter
	columns      []sql.Expression
	filters      []sql.Expression
	schema       sql.Schema
}

func (i *indexIter) Next() (sql.Row, error) {
	if iter == nil {
		iter, err := iterWithSelectors(...)
		...
	}

	v, err := idxValueIter.Next()
	// ...

	repo := pool.GetByID(value.ID)
	// ...

	currIter.NewIterator(repo)
	//...

	currIter.Next()
	// ...

}

func (i *indexIter) Close() error {
 // ...
}

```

**Comment by erizocosmico** [comment]
The context thing in `WithProjectFiltersAndIndex` is added here, but it's not merged yet: https://github.com/src-d/go-mysql-server/pull/185

Other than that, at first glance, it looks good.

**Comment by ajnavarro** [comment]
Sounds good.
