### ISSUE TITLE
Progress logging

### ISSUE THREAD

**Issue by eiso** [src-d/gitbase#454]
Often we're running queries or creating indexes that take a lot of time. Having any type of progress indicator (e.g. # of repos already processed) would be very useful. While not possible or common in most DB's, in gitbase case it should be very doable.

**Comment by ajnavarro** [comment]
There is no straightforward way to do it. On MySQL we have `SHOW FULL PROCESS LIST` command that can do the trick: https://dev.mysql.com/doc/refman/8.0/en/show-processlist.html

**Comment by kuba--** [comment]
I think we can reuse the `SHOW INDEX` query: https://dev.mysql.com/doc/refman/8.0/en/show-index.html
For instance we can put it in Comment:
> Comment
> Information about the index not described in its own column, such as disabled if the index is disabled.

**Comment by erizocosmico** [comment]
Implementing progress should be more or less trivial with partitions, since we now have the very-well defined chunks. Lower than the repository level I don't think it's viable to show progress, since we don't know the number of rows ahead of time (except maybe with indexes).

@ajnavarro since that needs some global registration on the engine, I think it could even be done in go-mysql-server (the query for sure needs to be on gms). We need something that keeps track globally of the queries that are running (which we currently do not have) and their progress and hooks so the queries can update the progress as they process stuff. I don't see any of this as something gitbase specific. We can use partitions to estimate the progress, but it's an iterator, though. So maybe we would need to precompute all partitions before and I'm not sure it's worth it just for having viewable progress.

@kuba-- what about queries without indexes? Besides, indexes already log their progress.

**Comment by ajnavarro** [comment]
@erizocosmico do this on go-mysql-server makes a lot of sense for me. We can implement a way to get total partition count if the implementor allows that (in the gitbase case, we know beforehand the number of repositories that we have). If we don't have the total number of partitions, we can provide just the number of processed partitions.

**Comment by erizocosmico** [comment]
Yep, that sounds good.
Also, we need to take into account that there might be multiple tables with different number of partitions. So we will need to find all tables in the query tree and track their processing stats.

**Comment by kuba--** [comment]
@erizocosmico - I overlooked full question and focused on:
> ...creating indexes that take a lot of time. 
I agree, for regular queries it will require totally different approach.

**Comment by erizocosmico** [comment]
Closing this and moving it to go-mysql-server.
