### ISSUE TITLE
[brainstorming] Improve queries that are using UAST functions

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#542]
Issue intended to talk about several ways to improve queries that are using bblfsh (UAST functions).

Any Idea can be added as a comment on that issue and after discussion will be added on the main comment and eventually added to gitbase.

- [X] add LRU cache to avoid duplicated calls to bblfsh
- [ ] list of blobs that are not parseable (related:https://github.com/bblfsh/client-go/issues/82) to avoid unnecessary calls to bblfsh

**Comment by kuba--** [comment]
- [ ] is it possible to have batch requests to UAST
- [ ] can we make kind of shortcut assumptions based on file extensions? For instance we cannot parse perl, and it's so unlikely that people, in the same repo will use the same extension for different files/languages. So if we tried to parse `.pl` and it turned out that it's a perl which we cannot parse then next time we don't need to try another `.pl` file from the same repo.

**Comment by erizocosmico** [comment]
@kuba-- regarding 2, afaik we already don't send the request to parse if the language is not supported on the bblfsh server.

**Comment by kuba--** [comment]
@erizocosmico really?
Y'day I saw tons of rpc errors regarding perl. I have to double check it.

Btw. Also for big files 50K+ we get rpc processed content error `DeadlineExceeded`. So maybe it doesn't make sense to send _big files_, because it takes some time for roundtrip and we get nothing because of 5sec timeout.

**Comment by ajnavarro** [comment]
Superseded by https://github.com/src-d/gitbase/issues/578

**Comment by ajnavarro** [comment]
Reopen.

**Comment by bzz** [comment]
on 
> Also for big files 50K+ we get rpc processed content error DeadlineExceeded

jfyi,  most probably you already know all that but sharing here for the sake of history: until https://github.com/bblfsh/client-go/issues/102 is released, `bblfshd` would fail on parsing files >4mb.

As for `DeadlineExceeded` - the timeout can be increased by passing by `.Context(ctx)` to ParseRequest

```go
	client, err := bblfsh.NewClient("0.0.0.0:9432")
        ctx, cancel := context.WithTimeout(context.Background(), 50*time.Second)
        resp, err := client.NewParseRequest().Context(ctx).ReadFile(srcFile).Do()
```

**Comment by erizocosmico** [comment]
Is there anything else here to be done?
