### ISSUE TITLE
Soft links not supported

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#547]
I tried starting a gitbase server pointing to a soft link `~/new_repos` which pointed to a directory `/mnt/disks/sdb/new_repos` which contains a bunch of cloned repositories.

When running `gitbase -d ~/new_repos` no repos were found, while running `gitbase -d /mnt/disks/sdb/new_repos` did find all of the repositories.

**Comment by BakeRolls** [comment]
Hi, since `filepath.Walk` doesn't follow symlinks, we could check the provided directories and optionally resolve them. Deeper links should probably still be ignored.

Please have a look at [my branch](https://github.com/src-d/gitbase/compare/master...BakeRolls:server-follow-symlink) for a very small implementation, if this solution would work for you.

**Comment by campoy** [comment]
Just tried and unfortunately it doesn't work.
If you send a PR I'm happy to review and try to see why it's not.

**Comment by ajnavarro** [comment]
@campoy did you test symlinks with the latest beta version?

**Comment by campoy** [comment]
Maybe I'm doing it wrong ... but it doesn't seem to be working.

I created a directory with a soft link pointing to a directory containing a bunch of repos, none of the repos were analyzed.

**Comment by kuba--** [comment]
@campoy - actually I cannot reproduce it. Which one is your case?
### Case 1 (symlink to folder with repos)
```sh
# download/clone some repositories to repos directory e.g.:
$ pga list -l python -f json | head -n 10 | jq -r '.sivaFilenames[]' | pga get -i -o repos

# create symlink to repos directory
$ ln -s repos repos-link

# start gitbase
$ ./gitbase server -d repos-link
```

### Case 2 (with symlink as subdirectory)
```sh
# download/clone somerepositories to repos directory e.g.:
$ pga list -l python -f json | head -n 10 | jq -r '.sivaFilenames[]' | pga get -i -o repos

# create another directory
$ mkdir repos2
$ cd repo2

# create symlink to repos subdirectory
$ ln -s ../repos/siva siva
$ cd ..

# start gitbase
$ ./gitbase server -d repos2
```

*Case 1* should work (because we resolve symlinks just for the top level), but when we traverse subdirectories we don't resolve any links, so *Case 2* doesn't work.

**Comment by campoy** [comment]
I think my case is actually somewhere in between:

There's a folder `repos` that contains a bunch of repositories.
Then I have another directory `home` that contains a `repos` soft link to the `repos` directory above.

I can try it again if needed, since it's been a while.

**Comment by kuba--** [comment]
ohh, so kind of a cycle?:
```
/repos
|-repo1
|-repo2
|...
|-home
     |-repos -> ../../repos
```

Because so far it's ok to pass a link to the repos folder, but repos cannot be links.
Anyway, if the structure is like the above one and you run gitbase:
` ./gitbase server -v -d /repos/home/repos`
it should work fine (so repo1, and repo2, ..) should be there.

**Comment by campoy** [comment]
I tried again and it worked, so I guess I was using an old version 👍
