### ISSUE TITLE
Support updates on gitbase

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#580]
To be able to support any kind data update, we need to emulate or achieve the transaction concept, to avoid queries on dirty or outdated data. Also, we need to support cache invalidation and index regeneration on updates.
I was thinking in two approaches to do it:

### Approach 1:
A copy of the data is managed by gitbase. A listener on the original folder checks if some file changed, generating gitbase events per repository. Using these events we can invalidate partition cache or regenerate partition indexes if needed.

The data will not be accessible until all the indexes are regenerated and all the caches are invalidated (transactions). All the queries executed on index generation will use the old index until the new one is ready.

Indexes could be regenerated in two ways:
- Regenerate the whole partition.
- Regenerate only affected rows.

This will depend on how precise are our events (just this file has been added or deleted, or check which objects changed depending on the updated or created packfile).

#### Pros:
- Easier to implement that Approach 2
- Less intrusive than Approach 2
- We can just sync a specific refspec and ignore the rest (only x,y and z references, per example).

#### Cons:
- Disk space usage
- How to sync status when gitbase is powered off and then on?

### Approach 2:

Gitbase is also a git server. Repository data is handled by gitbase. On each git push to the server, gitbase generates several events to update indexes or invalidate caches. The rest is working exactly as in Approach 1.

#### Pros:
- Less disk space usage than Approach 1
- If gitbase is off, data cannot change

#### Cons:
- Intrusive, you need to use gitbase as a git server
- we need to handle and keep all the data, no refspec filtering possible

**Comment by ajnavarro** [comment]
Next steps:
- Check what happens when we modify a repo now using gitbase
- Check how to interfere git on a git repository that we are reading
- Check server hooks on git

**Comment by kuba--** [comment]
Slightly related comments
---
Generally gitbase becomes more complex and more 3rd party service relies on it. That's why I think would be good to have a eventing system, so any service can subscribe on gitbase events (index created, index deleted, git push, etc.). 
We should be able to set where events should go (rabbit channel, ... any amqp interface).
Based on events you can make a decision about trigger rebuild of indexes, cleanup stuff, etc.
Also eventing can be a good diagnostic source. For instance you can telnet or listen on UDP particular port and see what's going on.

If w don't want to complicate gitbase too much (just treat it as a regular mysql server) I came across another approach, where another service was listening and parsing mysql logs and pushed events based on extracted information from logs (loosely coupled components), but it's sounds more as a external diagnostic source instead of relied, ordered pipeline of what happened.

**Comment by smola** [comment]
@jfontan @ajnavarro I guess we can consider this done by now. Of course there's further work on indexes, dataset versions, etc.
