### ISSUE TITLE
More clear error on unsupported IN using subqueries instead of expressions

### ISSUE THREAD

**Issue by campoy** [src-d/gitbase#622]
When running this request, I get a very unclear error. What is not supported exactly?

```go
SELECT *
FROM trees
WHERE tree_hash IN (
  SELECT tree_hash
  FROM commits
  WHERE commit_hash = '5e5f7e53896a171959c34483a60db5770a8abac0'
)
```

The error message doesn't necessarily help explain why this is not supported.

```
Query Failed - unknown error: unsupported syntax: &sqlparser.Subquery{Select:(*sqlparser.Select)(0xc000a5e340)}
```

**Comment by kuba--** [comment]
First of all the query should be (tree_entries instead of trees):

```sql
SELECT *
FROM tree_entries
WHERE tree_hash IN (  SELECT tree_hash  FROM commits  WHERE commit_hash = '5e5f7e53896a171959c34483a60db5770a8abac0');
```

So far we don't support subqueries for conditions/filters (it will require extra work for mysql - here is an open issue: https://github.com/src-d/go-mysql-server/issues/59)

This PR just adds an explicit error message: https://github.com/src-d/go-mysql-server/pull/552
