### ISSUE TITLE
gitbase plugins research. Check different alternatives.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/gitbase#676]
We need a way to add more functionality to gitbase without the need of recompiling. As an example, we would want to add new tables with another kind of info or some new user-defined function.

This task is to do some research about several plugins systems and the pros and cons of them. So far we should start with:
- Go plugin system
- Hashicorp go plugin system: https://github.com/hashicorp/go-plugin
- Add any other to the list if necessary

From them, we should check:
- Plugin versioning needs
- How the plugin system is communicating with the main go process we don't want to serialize a lot of data between plugins and application.
- Preliminary definition of some interfaces to be able to implement new tables or UDFs
- Check if would be worth it to implement at go-mysql-server level

**Comment by kuba--** [comment]
Good alternative to consider:
```
When we started using plugins (late 2012, early 2013), plugins over RPC were the only option since Go didn't support dynamic library loading. Today, Go supports the plugin standard library with a number of limitations. Since 2012, our plugin system has stabilized from tens of millions of users using it, and has many benefits we've come to value greatly.

For example, we use this plugin system in Vault where dynamic library loading is not acceptable for security reasons. That is an extreme example, but we believe our library system has more upsides than downsides over dynamic library loading and since we've had it built and tested for years, we'll continue to use it.

Shared libraries have one major advantage over our system which is much higher performance. In real world scenarios across our various tools, we've never required any more performance out of our plugin system and it has seen very high throughput, so this isn't a concern for us at the moment.
```

**Comment by kuba--** [comment]
### Brief overview
Most of the existing _go plugin_ solutions rely on communication over local network. Always it's kind of RPC-like approach. So if we want to go with this approach then  https://github.com/hashicorp/go-plugin package makes sense. It supports standard RPC and GRPC and it's well tested for 6+ years.
Personally (mainly because of performance) I prefer _language-native_ approach with libraries loaded into a process' memory.
Since version go-1.8 you can load plugins dynamically. But if you look closer to this solution it sounds to me _unfinished_ and makes code less _maintainable_ as rpc-like solution(s).

The new "plugin" package introduced in Go 1.8 doesn't work on windows. 
It provides the `Open()` function to load a shared library, which returns a `Plugin` object. The Plugin object has a `Lookup()` function that returns a `Symbol` as an `interface{}`. 
Sounds simple, but lets take a look into the super simple example - you have a function 
```go
func Sort(items []int) *[]int 
```
So, now if you want to call the function then you have to _lookup_ it, get the func. symbol and call it. Sounds simple but the syntax is _terrible_ (IMHO), because of casting from empty interfaces:
```go
symbol := p.Lookup("Sort")
sortFunc := symbol.(func([]int) *[]int) // <---- (╯°□°）╯︵ ┻━┻

sorted := sortFunc([]int{5, 2, 7, 6, 1, 3, 4, 8})
```
Moreover, if we change a signature of any function it will still compile and may crash, so changing all the casts can be painful.
Because, you have to know which function to lookup and what's the function signature is. It may turns out that we'll need a file with definitions (like a proto files in grpc).
Last but not least concern is error handling. If you load a plugin into the process and it paniced, your program will crash. 
In RPC-like approach your plugin works as an independent, small, local service/process. So if it crashed, you just lost a plugin but _the kernel_ still works.

### RPC vs GRPC
My first thought was to just stick to the standard library ("net/rpc"), but I think it will be another flavour of RPC service at @src-d. Most (or maybe even all) RPC services (like lookout) communicate over GRPC (with definitions in protobuf files).
I believe having something like a `.proto` files for plugins is helpful and makes maintenance a little bit painless.
Because communication is over the network, we'll need some kind of multiplexing all the connections. For standard RPC go-plugin package uses another library `https://github.com/hashicorp/yamux`.
In GRPC approach it relies on HTTP2 which already handles multiplexing.
So, I think it's better to stick to GRPC, because of HTTP2, which is kind of standard what may help later in potential troubleshooting.

### Recap 
Maybe `go-plugin` over GRPC sounds like an over-engineered, heavy solution just for a pluggable system. But because we're talking about distributed services, not OS kernel, we can sacrifice parts of performance to have more fault-tolerant, maintainable solution.
Also having communication over RPC let us run plugins as standalone/independent services.

**Comment by kuba--** [comment]
### Practical point of view
I played a little bit with `go-plugin` package and std. library plugin package. My goal was to create a simple plugin which will react `OnRule`. In other words I wanted to have kind of notifications when each rule begins/ends and react on this (so far just println).

It took me a while to create, generate and understand go-plugin api (concept of communication across all layers of abstraction) - typical _learning curve process_.
It turns out that to start plugin (as a grpc server) from mysql (as a grpc client) doesn't look super nice and readable. For instance:
```go
// We're a host. Start by launching the plugin process.
	client := plugin.NewClient(&plugin.ClientConfig{
//...
		Cmd:             exec.Command("sh", "-c", os.Getenv("RULE_PLUGIN")),
//...
	})

	// Connect via RPC
	rpcClient, err := client.Client()
	// Request the plugin
	raw, err := rpcClient.Dispense("rule_grpc")

	// We should have a Rule now! This feels like a normal interface
	// implementation but is in fact over an RPC connection.
	plugin := raw.(RulePlugin)
```
+ generated files = lot of boilerplate.

On other hand, criticised, by me native plugin solution was a way much simpler and faster. 
It took me just 5 minutes, to define super small/tiny interface with one function `OnRule`. 
Load a plugin and add to global registry in init function, and trigger all plugins for each rule.
Super simple to play with. No serialization needed. 
But no windows support and we have to figure out own fault-tolerant and versioning mechanism.

---

So, the question is how and where we want to use it? Is it just for us, or it will be public interface so other people can extend gitbase?
I can see plugins useful as an extension for other version control systems. You can load a svn and hg plugins and automagically have support for SVN and Mercurial.
