### ISSUE TITLE
Gitbase doesn't work on windows with mounted directory for indexes

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase#747]
Gitbase 0.19.0.

Screenshots because it's hard to copy-past from remote windows console.

Client:
<img width="928" alt="Screenshot 2019-03-22 at 16 18 34" src="https://user-images.githubusercontent.com/406916/54833439-6a27c800-4cbe-11e9-9a76-7af88f48e8b1.png">

Server:
<img width="1116" alt="Screenshot 2019-03-22 at 16 17 19" src="https://user-images.githubusercontent.com/406916/54833468-757af380-4cbe-11e9-8a85-f50a2fb90852.png">
<img width="1099" alt="Screenshot 2019-03-22 at 16 18 02" src="https://user-images.githubusercontent.com/406916/54833483-7ca20180-4cbe-11e9-9545-111c838e7ce5.png">

The error:
> unable to save the index
> open file: open ...: invalid argument

But the file is actually created on host file system:
<img width="1115" alt="Screenshot 2019-03-22 at 16 33 19" src="https://user-images.githubusercontent.com/406916/54834368-4d8c8f80-4cc0-11e9-9b79-82c9f341a21e.png">

I tried to read the source code and see where the error can come from. I found this line: https://github.com/pilosa/pilosa/blob/f2994736585a8aafc2f2c47c3698b7acd3b95373/fragment.go#L199 which looks like the right place.

I tried to reproduce it by creating simple script and running it inside docker with mounted directory:
```go
package main

import (
	"fmt"
	"os"
)

func main() {
	asPilosa := "/mounted/asPilosa"

	_, err := os.OpenFile(asPilosa, os.O_RDWR|os.O_CREATE|os.O_APPEND, 0666)
	if err != nil {
		fmt.Printf("open file as pilosa: %s\n", err)
	}
}
```

but no luck. It creates the file without error.

It's super inconvinient to debug inside remote desktop. So I didn't go further by rebuilding gitbase with extra debug messages.

**Comment by kuba--** [comment]
It can be a silly thing with `.dir`, but so far hard to say. Btw. I'm still wondering how it's gonna work on windows, because pilosa uses `Flocks` for locking.
I'll take a closer look.

**Comment by kuba--** [comment]
Question - so the index file (on linux/inside docker container) was created?
`/var/lib/gitbase/.../.pilosa/...`

Because generally pilosa doesn't work on windows, because of lack fo `Flock`, `Mmap`, and other posix/lock related stuff.
So the question is can we create index file inside docker container when it's mounted to the windows folder. Following code can test it out:
```go
package main

import pilosa "github.com/pilosa/pilosa"

func main() {
	idx, err := pilosa.NewIndex("/mounted/.pilosa", "idx-win")
	if err != nil {
		panic(err)
	}

	_, err = idx.CreateField("fld-win", pilosa.OptFieldTypeDefault())
	if err != nil {
		panic(err)
	}
}
```

**Comment by kuba--** [comment]
Following code can reproduce this issue:
```go
package main

import "github.com/pilosa/pilosa"

func main() {
        idx, err := pilosa.NewIndex("/mounted/pilosa", "idx-win")
        if err != nil {
                panic(err)
        }

        fld, err := idx.CreateField("fld-win", pilosa.OptFieldTypeDefault())
        if err != nil {
                panic(err)
        }
        rows := []uint64{1, 2, 1, 2, 1, 2, 1, 2, 1}
        cols := []uint64{1, 2, 3, 4, 5, 6, 7, 8, 9}

        err = fld.Import(rows,cols, nil)
        if err != nil {
                panic(err)
        }
        fld.Close()
        idx.Close()
}
```

I tested on windows inside a docker container. It happens only for `Import` (`SetBit` works fine).

**Comment by kuba--** [comment]
This is pilosa's issue. I'm not 100% sure where the problem is, but the way how pilosa opens/closes hierarchy of files (`/index/field/view/fragment/storage,cache`) doesn't work for mounted volumes. I assume one of the syscalls (Mmap, Flock, Munmap, ...) is a root cause.
Basically pilosa's fragment tries to open a file:
```go
r, e = syscall.Open(name, flag|syscall.O_CLOEXEC, syscallMode(perm))
		if e == nil {
			break
		}
```
which returns an error `invalid argument`. After deep dive into go's std. lib., it happens only when `File` pointer is nil. Calling directly `syscall.Open` works fine. So, definitively pilosa previous calls hide some attributes.

Definitively we don't want to replace `field.Import` by `SetBit`, because of performance reasons. So, I'll try to submit an issue to pilosa project.

**Comment by erizocosmico** [comment]
Waiting for https://github.com/src-d/go-mysql-server/issues/679 to be merged before the fix for this

**Comment by ajnavarro** [comment]
@erizocosmico already merged.

**Comment by kuba--** [comment]
Setting `syswrap.SetMaxMapCount(0)` in pilosa driver init function should solve the windows issue.

**Comment by erizocosmico** [comment]
PIlosa version bump in https://github.com/src-d/gitbase/pull/804. When it's merged, we will add the fix.

**Comment by kuba--** [comment]
But to fix it, I think it's better to call `syswrap.SetMaxMapCount(0)` in mysql (for instance `pilosa/driver.go` init).

**Comment by erizocosmico** [comment]
https://github.com/src-d/gitbase/pull/804 will fix this

**Comment by erizocosmico** [comment]
@smacker can you check now with current master?

**Comment by erizocosmico** [comment]
ping @smacker

**Comment by smacker** [comment]
<img width="1396" alt="Screenshot 2019-04-30 at 18 39 29" src="https://user-images.githubusercontent.com/406916/56978301-79c8e500-6b77-11e9-9f50-a375410d7bf0.png">
